name : Deploy Code
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Get Node
        uses: actions/setup-node@v3
      - name: Install Dependencies
        run: npm ci
      - name: Run Lint
        run: npm lint
      - name: Run tes
        run: npm test
      - name: Build the code
        run: npm run build
      - name: Deploy the code
        run: echo "Code Deployed...."